# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory_trans.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'inventory_trans.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inventory_trans.proto\"\x87\x01\n\x0fProto_Inventory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x18\n\x10transaction_type\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x1a\n\x12source_destination\x18\x04 \x01(\t\x12\x0f\n\x07remarks\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\"$\n\x16Proto_Inventory_Delete\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_trans_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTO_INVENTORY']._serialized_start=26
  _globals['_PROTO_INVENTORY']._serialized_end=161
  _globals['_PROTO_INVENTORY_DELETE']._serialized_start=163
  _globals['_PROTO_INVENTORY_DELETE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
