# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="teenmeem@gmail.com"

# Copy the current directory contents into the container at /code
COPY . /app/

# Set the working directory in the container
WORKDIR /app

#RUN apt-get update && apt-get install -y \
#    build-essential \
#    libpq-dev \
    # protobuf-compiler \
    # && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install dependencies including development ones
RUN poetry install

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]
